const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const IMG_DIR = __dirname;
const SRC_DIR = path.resolve(__dirname, 'src');
const DIST_DIR = path.resolve(__dirname, 'dist');

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

function copyDir(src, dest) {
  ensureDir(dest);
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      copyDir(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

// 1. Build base64 images map
console.log('Reading images from', IMG_DIR);
const images = {};
const files = fs.readdirSync(IMG_DIR).filter(f => f.endsWith('.jpg') || f.endsWith('.jpeg') || f.endsWith('.png'));
for (const file of files) {
  const key = file.replace(/\.(jpg|jpeg|png)$/, '');
  const data = fs.readFileSync(path.join(IMG_DIR, file));
  const ext = path.extname(file).slice(1);
  const mime = ext === 'jpg' || ext === 'jpeg' ? 'image/jpeg' : 'image/png';
  images[key] = `data:${mime};base64,${data.toString('base64')}`;
  console.log(`  Embedded: ${file} (${(data.length / 1024).toFixed(1)} KB)`);
}
console.log(`Total images: ${Object.keys(images).length}`);

// 2. Copy src to dist (overwrite in-place, don't delete dist/)
console.log('Copying src to dist...');
copyDir(SRC_DIR, DIST_DIR);

// 3. Write images.js
const imagesJs = `// Auto-generated by build.js — do not edit\nconst IMAGES = ${JSON.stringify(images)};\n`;
ensureDir(path.join(DIST_DIR, 'js'));
fs.writeFileSync(path.join(DIST_DIR, 'js', 'images.js'), imagesJs);
console.log(`Written dist/js/images.js (${(imagesJs.length / 1024 / 1024).toFixed(2)} MB)`);

// 4. Generate PWA icons (simple colored squares)
function generateIcon(size) {
  // Create a simple SVG icon and convert to a basic PNG-like placeholder
  // For a real app you'd use canvas, but for portability we'll create an SVG
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">
  <defs>
    <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" style="stop-color:#c88a7e"/>
      <stop offset="100%" style="stop-color:#b07468"/>
    </linearGradient>
  </defs>
  <rect width="${size}" height="${size}" rx="${size * 0.15}" fill="url(#bg)"/>
  <text x="50%" y="52%" dominant-baseline="middle" text-anchor="middle"
        font-family="Arial,sans-serif" font-weight="bold" font-size="${size * 0.3}px" fill="white">21</text>
  <text x="50%" y="78%" dominant-baseline="middle" text-anchor="middle"
        font-family="Arial,sans-serif" font-size="${size * 0.12}px" fill="rgba(255,255,255,0.9)">HIP</text>
</svg>`;
  return svg;
}

ensureDir(path.join(DIST_DIR, 'icons'));
fs.writeFileSync(path.join(DIST_DIR, 'icons', 'icon-192.svg'), generateIcon(192));
fs.writeFileSync(path.join(DIST_DIR, 'icons', 'icon-512.svg'), generateIcon(512));
console.log('Generated PWA icons');

// 5. Stamp sw.js with a unique build hash so updates invalidate the old cache
const buildHash = crypto.randomBytes(6).toString('hex');
const swPath = path.join(DIST_DIR, 'sw.js');
let swContent = fs.readFileSync(swPath, 'utf8');
swContent = swContent.replace('__BUILD_HASH__', buildHash);
fs.writeFileSync(swPath, swContent);
console.log(`Stamped sw.js with build hash: ${buildHash}`);

console.log('\nBuild complete! Serve the dist/ folder to run the app.');
