// 21-Day Hip Opening Challenge — Complete pose data
// Image keys map to entries in IMAGES (generated by build.js)
// Poses follow the user's specified order per day

const CHALLENGE_DATA = [
  {
    day: 1,
    poses: [
      { id: "d1p1", name: "Pigeon — Right", imageKey: "day1_pigeon_pose_1_2", duration: 300 },
      { id: "d1p2", name: "Pigeon — Left", imageKey: "day1_pigeon_pose_1_2", duration: 300 },
      { id: "d1p3", name: "Butterfly", imageKey: "day1_Butterfly_pose_3", duration: 300 },
    ]
  },
  {
    day: 2,
    poses: [
      { id: "d2p1", name: "Blaster — Right", imageKey: "day2_Blaster_pose_1_2", duration: 300 },
      { id: "d2p2", name: "Blaster — Left", imageKey: "day2_Blaster_pose_1_2", duration: 300 },
      { id: "d2p3", name: "Passive Squat", imageKey: "day2_Passive_squat_pose_3", duration: 300 },
    ]
  },
  {
    day: 3,
    poses: [
      { id: "d3p1", name: "Happy Baby", imageKey: "day3_Happy_Baby_pose_1", duration: 300 },
      { id: "d3p2", name: "Thread the Needle (Supine) — Right", imageKey: "day3_Thread_the_Needle_pose_2_3", duration: 300 },
      { id: "d3p3", name: "Thread the Needle (Supine) — Left", imageKey: "day3_Thread_the_Needle_pose_2_3", duration: 300 },
    ]
  },
  {
    day: 4,
    poses: [
      { id: "d4p1", name: "Frog", imageKey: "day4_Frog_pose_1", duration: 300 },
      { id: "d4p2", name: "Jackknife Blaster — Right", imageKey: "day4_Jackknife_Blaster_pose_2_3", duration: 300 },
      { id: "d4p3", name: "Jackknife Blaster — Left", imageKey: "day4_Jackknife_Blaster_pose_2_3", duration: 300 },
    ]
  },
  {
    day: 5,
    poses: [
      { id: "d5p1", name: "Scissors — Right", imageKey: "day5_Scissors_pose_1_2", duration: 300 },
      { id: "d5p2", name: "Scissors — Left", imageKey: "day5_Scissors_pose_1_2", duration: 300 },
      { id: "d5p3", name: "Lightning Bolt", imageKey: "day5_Lightning_Bolt_pose_3", duration: 300 },
    ]
  },
  {
    day: 6,
    poses: [
      { id: "d6p1", name: "Zorro — Right", imageKey: "day6_Zorro_pose_1_2", duration: 300 },
      { id: "d6p2", name: "Zorro — Left", imageKey: "day6_Zorro_pose_1_2", duration: 300 },
      { id: "d6p3", name: "Supine Butterfly", imageKey: "day6_Supine_Butterfly_pose_3", duration: 300 },
    ]
  },
  {
    day: 7,
    poses: [
      { id: "d7p1", name: "Thread the Needle @ Wall — Right", imageKey: "day7_Wall_Thread_the_Needle_pose_1_2", duration: 300 },
      { id: "d7p2", name: "Thread the Needle @ Wall — Left", imageKey: "day7_Wall_Thread_the_Needle_pose_1_2", duration: 300 },
      { id: "d7p3", name: "Prone Butterfly", imageKey: "day7_Prone_butterfly_pose_3", duration: 300 },
    ]
  },
  {
    day: 8,
    poses: [
      { id: "d8p1", name: "Ninja Squats — Right", imageKey: "day8_Ninja_Squats_pose_1_2", duration: 300 },
      { id: "d8p2", name: "Ninja Squats — Left", imageKey: "day8_Ninja_Squats_pose_1_2", duration: 300 },
      { id: "d8p3", name: "Lateral Chain Stretch — Right", imageKey: "day8_Lateral_Chain_Stretch_pose_3_4", duration: 300 },
      { id: "d8p4", name: "Lateral Chain Stretch — Left", imageKey: "day8_Lateral_Chain_Stretch_pose_3_4", duration: 300 },
    ]
  },
  {
    day: 9,
    poses: [
      { id: "d9p1", name: "Psoas Blaster (Chair) — Right", imageKey: "day9_Chair_Psoas_Blaster_pose_1_2", duration: 300 },
      { id: "d9p2", name: "Psoas Blaster (Chair) — Left", imageKey: "day9_Chair_Psoas_Blaster_pose_1_2", duration: 300 },
      { id: "d9p3", name: "Reclined Scissors — Right", imageKey: "day9_Reclined_Scissors_pose_3_4", duration: 300 },
      { id: "d9p4", name: "Reclined Scissors — Left", imageKey: "day9_Reclined_Scissors_pose_3_4", duration: 300 },
    ]
  },
  {
    day: 10,
    poses: [
      { id: "d10p1", name: "Blaster Twist — Right", imageKey: "day10_Blaster_Twist_pose_1_2", duration: 300 },
      { id: "d10p2", name: "Blaster Twist — Left", imageKey: "day10_Blaster_Twist_pose_1_2", duration: 300 },
      { id: "d10p3", name: "Squat Twist — Right", imageKey: "day10_Squat_Twist_pose_3_4", duration: 300 },
      { id: "d10p4", name: "Squat Twist — Left", imageKey: "day10_Squat_Twist_pose_3_4", duration: 300 },
    ]
  },
  {
    day: 11,
    poses: [
      { id: "d11p1", name: "Double Pigeon — Right", imageKey: "day11_Double_pigeon_pose_1_2", duration: 300 },
      { id: "d11p2", name: "Double Pigeon — Left", imageKey: "day11_Double_pigeon_pose_1_2", duration: 300 },
      { id: "d11p3", name: "Bound Butterfly", imageKey: "day11_Bound_Butterfly_pose_3", duration: 300 },
    ]
  },
  {
    day: 12,
    poses: [
      { id: "d12p1", name: "Eagle Fold — Right", imageKey: "day12_Eagle_Fold_pose_1_2", duration: 300 },
      { id: "d12p2", name: "Eagle Fold — Left", imageKey: "day12_Eagle_Fold_pose_1_2", duration: 300 },
      { id: "d12p3", name: "Cross-Thread — Right", imageKey: "day12_Cross_thread_pose_3_4", duration: 300 },
      { id: "d12p4", name: "Cross-Thread — Left", imageKey: "day12_Cross_thread_pose_3_4", duration: 300 },
    ]
  },
  {
    day: 13,
    poses: [
      { id: "d13p1", name: "Swiss Army Knife — Right", imageKey: "day13_Swiss_army_knife_pose_1_2", duration: 300 },
      { id: "d13p2", name: "Swiss Army Knife — Left", imageKey: "day13_Swiss_army_knife_pose_1_2", duration: 300 },
      { id: "d13p3", name: "Saddle", imageKey: "day13_Saddle_pose_3", duration: 300 },
    ]
  },
  {
    day: 14,
    poses: [
      { id: "d14p1", name: "Butterfly Squat", imageKey: "day14_Butterfly_Squat_pose_1", duration: 300 },
      { id: "d14p2", name: "Half Lightning Bolt — Right", imageKey: "day14_Half_lighting_Bolt_pose_2_3", duration: 300 },
      { id: "d14p3", name: "Half Lightning Bolt — Left", imageKey: "day14_Half_lighting_Bolt_pose_2_3", duration: 300 },
    ]
  },
  {
    day: 15,
    poses: [
      { id: "d15p1", name: "Fallen Blaster — Right", imageKey: "day15_Fallen_Blaster_pose_1_2", duration: 300 },
      { id: "d15p2", name: "Fallen Blaster — Left", imageKey: "day15_Fallen_Blaster_pose_1_2", duration: 300 },
      { id: "d15p3", name: "A-Baby — Right", imageKey: "day15_A_Baby_pose_3_4", duration: 300 },
      { id: "d15p4", name: "A-Baby — Left", imageKey: "day15_A_Baby_pose_3_4", duration: 300 },
    ]
  },
  {
    day: 16,
    poses: [
      { id: "d16p1", name: "Standing Pigeon — Right", imageKey: "day16_Standing_Pigeon_pose_3_4", duration: 300 },
      { id: "d16p2", name: "Standing Pigeon — Left", imageKey: "day16_Standing_Pigeon_pose_3_4", duration: 300 },
      { id: "d16p3", name: "Standing Psoas — Right", imageKey: "day16_Standing_Psoas_pose_1_2", duration: 300 },
      { id: "d16p4", name: "Standing Psoas — Left", imageKey: "day16_Standing_Psoas_pose_1_2", duration: 300 },
    ]
  },
  {
    day: 17,
    poses: [
      { id: "d17p1", name: "Sage Fold — Right", imageKey: "day17_Sage_Fold_pose_1_2", duration: 300 },
      { id: "d17p2", name: "Sage Fold — Left", imageKey: "day17_Sage_Fold_pose_1_2", duration: 300 },
      { id: "d17p3", name: "Long Butterfly", imageKey: "day17_Long_Butterfly_pose_3", duration: 300 },
    ]
  },
  {
    day: 18,
    poses: [
      { id: "d18p1", name: "Eagle Legs — Right", imageKey: "day18_Eagle_legs_pose_1_2", duration: 300 },
      { id: "d18p2", name: "Eagle Legs — Left", imageKey: "day18_Eagle_legs_pose_1_2", duration: 300 },
      { id: "d18p3", name: "Chair Squat — Right", imageKey: "day18_Chair_Squat_pose_3_4", duration: 300 },
      { id: "d18p4", name: "Chair Squat — Left", imageKey: "day18_Chair_Squat_pose_3_4", duration: 300 },
    ]
  },
  {
    day: 19,
    poses: [
      { id: "d19p1", name: "Twisted Pigeon — Right", imageKey: "day19_Twisted_pigeon_pose_1_2", duration: 300 },
      { id: "d19p2", name: "Twisted Pigeon — Left", imageKey: "day19_Twisted_pigeon_pose_1_2", duration: 300 },
      { id: "d19p3", name: "Bound Baby — Right", imageKey: "day19_Bound_baby_pose_3_4", duration: 300 },
      { id: "d19p4", name: "Bound Baby — Left", imageKey: "day19_Bound_baby_pose_3_4", duration: 300 },
    ]
  },
  {
    day: 20,
    poses: [
      { id: "d20p1", name: "Seated Pigeon — Right", imageKey: "day20_Seated_pigeon_pose_1_2", duration: 300 },
      { id: "d20p2", name: "Seated Pigeon — Left", imageKey: "day20_Seated_pigeon_pose_1_2", duration: 300 },
      { id: "d20p3", name: "Railroad Squat", imageKey: "day20_Railway_squat_pose_3", duration: 300 },
    ]
  },
  {
    day: 21,
    poses: [
      { id: "d21p1", name: "Prayer Squat", imageKey: "day21_Prayer_squat_pose_3", duration: 300 },
      { id: "d21p2", name: "Thunderbolt — Right", imageKey: "day21_Thunderbolt_pose_1_2", duration: 300 },
      { id: "d21p3", name: "Thunderbolt — Left", imageKey: "day21_Thunderbolt_pose_1_2", duration: 300 },
    ]
  },
];
